# Fastfile

default_platform(:ios)

platform :ios do

    # Before running a lane, make sure to install the app dependencies
    before_all do
        install_pods
        ensure_git_status_clean
        install_npm_dependencies
    end

    desc "Run Jest unit tests"
    lane :test do
        sh "npm test"
    end

    desc "Build the iOS app"
    lane :build do
        # Sync code signing credentials using match
        match(type: "appstore") # Use 'development' or 'adhoc' as needed
        build_app(
            workspace: ENV["WORKSPACE"],
            scheme: ENV["SCHEME"]
        )
    end

    desc "Deploy a new version to the App Store"
    lane :release do
        # Increment the build number
        increment_build_number

        # Build the app
        build

        # Push a new release to the App Store
        upload_to_app_store(
        skip_metadata: true, # Set to false if you want to upload metadata
        skip_screenshots: true, # Set to false if you want to upload screenshots
        force: true # Skip HTTPOK Error
        )
    end

    # Private lane to install CocoaPods dependencies
    private_lane :install_pods do
        
        Dir.chdir("../ios") do
            puts "Changed to Directory: #{Dir.pwd}"
            if File.exist?("Podfile")
                puts "Found Podfile!"
            else
                puts "Podfile not found!"
            end
        end
        puts "Debug:"
        puts "Changed to Directory: #{Dir.pwd}"
        fastlane_dir = %x(pwd)
        absolute_path = Pathname.new(File.expand_path(fastlane_dir)).parent
        puts "Absolute Path: #{absolute_path}"
        cocoapods(
            repo_update: true,
            podfile: "./ios/Podfile"
        )
    end
end
