# Fastfile

default_platform(:ios)

platform :ios do

    # Before running a lane, make sure to install the app dependencies
    before_all do
        # install_pods
        # ensure_git_status_clean
    end

    lane :create_keys do
        match(type: "development", force_for_new_devices: true, git_basic_authorization: ENV["GIT_BASIC_AUTHORIZATION"])
        match(type: "adhoc", force_for_new_devices: true)
        match(type: "appstore")
    end

    desc "Download keys"
    lane :download_keys do
        match(type: "development", readonly: true)
        match(type: "adhoc", readonly: true)
        match(type: "appstore", readonly: true)
    end

    desc "Run Jest unit tests"
    lane :test do
        sh "npm test"
    end

    desc 'Build the iOS application.'
    lane :build do
        download_keys
        increment_build_number(xcodeproj: './ios/HarnessReact.xcodeproj')
        ENV['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        gym(
            scheme: 'HarnessReact', 
            project: './ios/HarnessReact.xcodeproj',
            clean: true,
            export_method: 'app-store',
            export_team_id: 'ZLX9RDU5FZ'
        )
    end



    desc "Build the iOS app"
    lane :beta do
        # Sync code signing credentials using match
        # match(type: "appstore") # Use 'development' or 'adhoc' as needed
        # increment_build_number
        # git_commit(path: "../ios/#{ENV["SCHEME"]}/Info.plist", message: "Increment build number to #{get_build_number}")
        debug_lane
        build
        pilot
        commit_version_bump(message: 'Bump build', xcodeproj: './ios/HarnessReact.xcodeproj')
        push_to_git_remote
        
        # gym(scheme: ENV["SCHEME"], project: './ios/HarnessReact.xcodeproj')
        # build_app(
        #     workspace: ENV["WORKSPACE"],
        #     scheme: ENV["SCHEME"]
        # )
    end

    lane :debug_lane do
        puts "Current Directory: #{Dir.pwd}"
        sh "ls -la"
    end


    desc "Deploy a new version to the App Store"
    lane :release do
        # Increment the build number
        increment_build_number

        # Build the app
        build

        # Push a new release to the App Store
        upload_to_app_store(
        skip_metadata: true, # Set to false if you want to upload metadata
        skip_screenshots: true, # Set to false if you want to upload screenshots
        force: true # Skip HTTPOK Error
        )
    end

    # Private lane to install CocoaPods dependencies
    private_lane :install_pods do
        
        # Dir.chdir("../ios") do
        #     puts "Changed to Directory: #{Dir.pwd}"
        #     if File.exist?("Podfile")
        #         puts "Found Podfile!"
        #     else
        #         puts "Podfile not found!"
        #     end
        # end
        puts "Debug:"
        puts "Changed to Directory: #{Dir.pwd}"
        fastlane_dir = %x(pwd)
        absolute_path = Pathname.new(File.expand_path(fastlane_dir)).parent
        puts "Fastlane Dir: #{absolute_path}"
        puts "Absolute Path: #{absolute_path}"
        ENV['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        cocoapods(
            repo_update: true,
            podfile: "#{absolute_path}/ios/Podfile"
        )
    end

end
